### ISSUE TITLE
使用主题失败, 希望提供一个完整版的使用Demo

### ISSUE THREAD

**Issue by YellowTulipShow** [wujun234/hexo-theme-tree#5]
类似于这种的:

![图片](https://user-images.githubusercontent.com/29710592/76585177-b5169d00-6518-11ea-8bd9-180091ec6631.png)

主要是看 _config.yml 文件 包引用文件的配置项, 

![图片](https://user-images.githubusercontent.com/29710592/76585242-decfc400-6518-11ea-8858-be2c0e0f94e6.png)

我在生成步骤出错, 安装了 markdown-it 文章内容是我自己写的内容 地址是: https://github.com/YellowTulipShow/-ArticleNotes 基本上是直接全部拷贝到 source/_posts/ 下的, 基本上没有做额外的操作

**Comment by YellowTulipShow** [comment]
完整的仓库地址: https://gitee.com/YellowTulipShow/TestHexo.git

**Comment by wujun234** [comment]
_config.yml 文件没有任何跟主题有关的配置项

**Comment by wujun234** [comment]
我的 _config.yml 文件里 Markdown-it 的配置是这样的

```
# Markdown-it config
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: false
    linkify: true
    typographer: true
    quotes: '“”‘’'
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
  anchors:
    level: 2
    collisionSuffix: 'v'
    permalink: true
    permalinkClass: header-anchor
    permalinkSymbol: ''
```
